### ISSUE TITLE
example scripts dont work with current module

### ISSUE THREAD

**Issue by stuliveshere** [stuliveshere/PySeis-archive#6]
example scripts import toolbox - this fails with import PySeis

**Comment by Andersongeofisco** [comment]
HI @smithkevinc 
Is there a tutorial in some place to seismic data processing? I would like to use python to seismic data processing but I am a beginner python programmer. 
Thanks!

**Comment by stuliveshere** [comment]
To be honest the main code in PySeis is a bit of a mess at the moment.

Try

*https://github.com/stuliveshere/SeismicProcessing2015
<https://github.com/stuliveshere/SeismicProcessing2015>*

It contains exercises as well as a stable version of the code.

The staff folders contain a tex folder which has the prac sheet as well as
full source code at the end. Note this project is a teaching project for
both python and seismic - if you want to work through it i'm happy to
answer any questions.

Cheers,

Stu

**Comment by Andersongeofisco** [comment]
Thanks Very much for your help! I Will try.

**Comment by Andersongeofisco** [comment]
That's exactly what I was looking for. I've been working with FORTRAN for a long time, but now I wanted to start learning another programming language. I chose python. Actually I was behind 3D visualization, but mastering the language is the first step.
I will train using these modules. If I have any questions, may I ask?
 Thank you!

**Comment by stuliveshere** [comment]
Ask away.

Cheers,
Stu

**Comment by Andersongeofisco** [comment]
Sorry to bother you again, but I have a question. The codes are working perfectly, but the seismic data (raw.su) is not in the directories, I downloaded directly on the internet, but I do not know the format of the data (1981-39) that I found in the site https: //energy.usgs .gov / GeochemistryGeophysics / SeismicDataProcessingInterpretation / NPRASeismicDataArchive.aspx.

If it's in segy I can use seismic unix to convert the data.

I'm taking this class step by step: https://github.com/stuliveshere/SeismicProcessing2015

**Comment by stuliveshere** [comment]
You should be able to download the segy files from that website. I've added
a screen shot of what I get.   You will need to convert them to su. It can
be done in pyseis, but seismix unix is probably easier to get started.

raw.su is all of the segys converted to su and combined into a single file
with # cat file1.su file2.su > raw.su

If you get stuck
https://drive.google.com/open?id=1HLr3Hs6J1x4V9ZGfvvvme_x1_2Id-Fnn

it's 524MB.

Cheers,

stu

Cheers,
Stu

**Comment by Andersongeofisco** [comment]
![erro-1](https://user-images.githubusercontent.com/33261554/44915041-498b2700-ad08-11e8-8bc1-3935ddd07047.png)

**Comment by Andersongeofisco** [comment]
I found this error now. I think this error is because the code can't read the ns  value in the header.

**Comment by stuliveshere** [comment]
IO is being ported to a different method, closing due to age
