### ISSUE TITLE
How to read p190 files

### ISSUE THREAD

**Issue by satishgc227** [stuliveshere/PySeis-archive#7]
Kindly help me how to read p190 files.

Regards.

**Comment by stuliveshere** [comment]
Hi,

As you can probably tell from the delay in reply PySeis is not being maintained at the moment.

It is however being actively used, mostly to manipulate segy files.

If you link me to the p190 file standard I can give it a quick scan over and have a look at how hard it would be to implement.

Cheers,
Stu

**Comment by stuliveshere** [comment]
closing due to lack of response
